### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by MorrisNein** [ITMO-NSS-team/GAMLET#28]
- [x] ITMO badge
- [x] Workflow badge for #24 
- [x] CodeCov badge for #23
- [ ] Documentation badge for #26
- [x] More ?

**Comment by DRMPN** [comment]
docs badge is left
